/**
 * Topónimos frecuentes en cotizaciones de agencias españolas.
 * Usado por extractPlaceCandidates — no es un geocoder.
 */
export const TOP_DESTINATIONS: string[] = [
  // España — islas y costa
  "Ibiza",
  "Formentera",
  "Mallorca",
  "Menorca",
  "Palma",
  "Tenerife",
  "Gran Canaria",
  "Lanzarote",
  "Fuerteventura",
  "La Palma",
  "La Gomera",
  "El Hierro",
  "Canarias",
  "Costa del Sol",
  "Marbella",
  "Málaga",
  "Benidorm",
  "Alicante",
  "Valencia",
  "Barcelona",
  "Sitges",
  "Costa Brava",
  "Girona",
  "Tarragona",
  "Salou",
  "Cambrils",
  "Andalucía",
  "Sevilla",
  "Granada",
  "Córdoba",
  "Cádiz",
  "Jerez",
  "Ronda",
  "Nerja",
  "Torremolinos",
  "Fuengirola",
  "Estepona",
  "Puerto Banús",
  "Almería",
  "Murcia",
  "Cartagena",
  "Galicia",
  "Santiago de Compostela",
  "A Coruña",
  "Vigo",
  "San Sebastián",
  "Donostia",
  "Bilbao",
  "Santander",
  "Asturias",
  "Gijón",
  "Oviedo",
  "Picos de Europa",
  "Zaragoza",
  "Madrid",
  "Toledo",
  "Segovia",
  "Ávila",
  "Salamanca",
  "León",
  "Burgos",
  "Valladolid",
  "Pamplona",
  "Logroño",
  "Cáceres",
  "Mérida",
  "Badajoz",
  "Extremadura",
  "Castilla",
  "La Rioja",
  "Navarra",
  "País Vasco",
  "Euskadi",
  "Cataluña",
  "Catalunya",
  "Andorra",
  // Portugal
  "Lisboa",
  "Lisbon",
  "Porto",
  "Oporto",
  "Algarve",
  "Faro",
  "Madeira",
  "Funchal",
  "Azores",
  "Sintra",
  "Cascais",
  "Évora",
  // Francia
  "París",
  "Paris",
  "Niza",
  "Nice",
  "Marsella",
  "Lyon",
  "Burdeos",
  "Bordeaux",
  "Estrasburgo",
  "Toulouse",
  "Provenza",
  "Provençe",
  "Costa Azul",
  "Córcega",
  "Corsica",
  "Normandía",
  "Bretaña",
  "Chamonix",
  "Annecy",
  "Aviñón",
  // Italia
  "Roma",
  "Rome",
  "Florencia",
  "Florence",
  "Venecia",
  "Venice",
  "Milán",
  "Milan",
  "Nápoles",
  "Naples",
  "Amalfi",
  "Positano",
  "Capri",
  "Sicilia",
  "Sicily",
  "Cerdeña",
  "Sardinia",
  "Cerdeña",
  "Toscana",
  "Tuscany",
  "Verona",
  "Bolonia",
  "Bologna",
  "Turín",
  "Turin",
  "Génova",
  "Pisa",
  "Siena",
  "Lake Como",
  "Lago de Como",
  "Cinque Terre",
  "Pompeya",
  "Pompeii",
  "Taormina",
  "Palermo",
  "Catania",
  "Apulia",
  "Puglia",
  // Grecia
  "Atenas",
  "Athens",
  "Santorini",
  "Mykonos",
  "Creta",
  "Crete",
  "Rodas",
  "Rhodes",
  "Corfú",
  "Corfu",
  "Zante",
  "Zakynthos",
  "Milos",
  "Paros",
  "Naxos",
  "Tesalónica",
  "Thessaloniki",
  // Reino Unido / Irlanda
  "Londres",
  "London",
  "Edimburgo",
  "Edinburgh",
  "Dublín",
  "Dublin",
  "Manchester",
  "Bath",
  "Oxford",
  "Cambridge",
  "Glasgow",
  "Belfast",
  "Galway",
  "Cork",
  // Centro Europa
  "Ámsterdam",
  "Amsterdam",
  "Bruselas",
  "Brussels",
  "Brujas",
  "Bruges",
  "Gante",
  "Ginebra",
  "Geneva",
  "Zúrich",
  "Zurich",
  "Berna",
  "Lucerna",
  "Interlaken",
  "Zermatt",
  "Viena",
  "Vienna",
  "Salzburgo",
  "Salzburg",
  "Innsbruck",
  "Praga",
  "Prague",
  "Budapest",
  "Cracovia",
  "Krakow",
  "Varsovia",
  "Warsaw",
  "Berlín",
  "Berlin",
  "Múnich",
  "Munich",
  "Hamburgo",
  "Fráncfort",
  "Frankfurt",
  "Colonia",
  "Cologne",
  "Dresde",
  "Heidelberg",
  "Estocolmo",
  "Stockholm",
  "Copenhague",
  "Copenhagen",
  "Oslo",
  "Helsinki",
  "Reikiavik",
  "Reykjavik",
  "Islandia",
  "Iceland",
  "Noruega",
  "Fiordos",
  // Mediterráneo Este / Turquía
  "Estambul",
  "Istanbul",
  "Antalya",
  "Bodrum",
  "Capadocia",
  "Cappadocia",
  "Dubrovnik",
  "Split",
  "Zagreb",
  "Croacia",
  "Croatia",
  "Montenegro",
  "Kotor",
  "Budva",
  "Albania",
  "Tirana",
  "Malta",
  "La Valeta",
  "Valletta",
  "Chipre",
  "Cyprus",
  "Pafos",
  "Larnaca",
  // Norte de África
  "Marrakech",
  "Marruecos",
  "Morocco",
  "Casablanca",
  "Fez",
  "Fes",
  "Rabat",
  "Tánger",
  "Tangier",
  "Essaouira",
  "Agadir",
  "Túnez",
  "Tunisia",
  "Egipto",
  "Egypt",
  "El Cairo",
  "Cairo",
  "Luxor",
  "Asuán",
  "Aswan",
  "Sharm el Sheikh",
  "Hurghada",
  // Caribe / América
  "Cancún",
  "Cancun",
  "Riviera Maya",
  "Playa del Carmen",
  "Tulum",
  "Cozumel",
  "Punta Cana",
  "República Dominicana",
  "Santo Domingo",
  "Cuba",
  "La Habana",
  "Havana",
  "Varadero",
  "Jamaica",
  "Montego Bay",
  "Barbados",
  "Bahamas",
  "Aruba",
  "Curaçao",
  "Curazao",
  "Puerto Rico",
  "San Juan",
  "Miami",
  "Orlando",
  "Nueva York",
  "New York",
  "NYC",
  "Los Ángeles",
  "Los Angeles",
  "San Francisco",
  "Las Vegas",
  "Chicago",
  "Boston",
  "Washington",
  "Seattle",
  "Toronto",
  "Vancouver",
  "Montreal",
  "Québec",
  "Quebec",
  "México",
  "Mexico",
  "Ciudad de México",
  "Mexico City",
  "CDMX",
  "Guadalajara",
  "Oaxaca",
  "Ciudad de México",
  "Costa Rica",
  "San José",
  "Panamá",
  "Panama",
  "Colombia",
  "Bogotá",
  "Cartagena de Indias",
  "Medellín",
  "Perú",
  "Peru",
  "Lima",
  "Cusco",
  "Cuzco",
  "Machu Picchu",
  "Chile",
  "Santiago de Chile",
  "Santiago",
  "Patagonia",
  "Buenos Aires",
  "Argentina",
  "Bariloche",
  "Mendoza",
  "Brasil",
  "Brazil",
  "Río de Janeiro",
  "Rio de Janeiro",
  "São Paulo",
  "Sao Paulo",
  "Salvador de Bahía",
  "Florianópolis",
  "Iguazú",
  "Iguazu",
  // Oriente Medio
  "Dubái",
  "Dubai",
  "Abu Dhabi",
  "Abu Dhabí",
  "Qatar",
  "Doha",
  "Omán",
  "Oman",
  "Mascate",
  "Muscat",
  "Jordania",
  "Jordan",
  "Amman",
  "Petra",
  "Israel",
  "Tel Aviv",
  "Jerusalén",
  "Jerusalem",
  // Asia
  "Tokio",
  "Tokyo",
  "Kioto",
  "Kyoto",
  "Osaka",
  "Japón",
  "Japan",
  "Seúl",
  "Seoul",
  "Corea",
  "Korea",
  "Pekín",
  "Beijing",
  "Shanghái",
  "Shanghai",
  "Hong Kong",
  "Taiwán",
  "Taiwan",
  "Taipei",
  "Tailandia",
  "Thailand",
  "Bangkok",
  "Phuket",
  "Chiang Mai",
  "Krabi",
  "Koh Samui",
  "Vietnam",
  "Hanói",
  "Hanoi",
  "Ho Chi Minh",
  "Saigón",
  "Saigon",
  "Camboya",
  "Cambodia",
  "Siem Reap",
  "Angkor",
  "Singapur",
  "Singapore",
  "Malasia",
  "Malaysia",
  "Kuala Lumpur",
  "Bali",
  "Indonesia",
  "Yakarta",
  "Jakarta",
  "Filipinas",
  "Philippines",
  "Manila",
  "Boracay",
  "Maldivas",
  "Maldives",
  "Sri Lanka",
  "Colombo",
  "India",
  "Delhi",
  "Nueva Delhi",
  "Mumbai",
  "Bombay",
  "Goa",
  "Jaipur",
  "Agra",
  "Nepal",
  "Katmandú",
  "Kathmandu",
  // África / Índico
  "Sudáfrica",
  "South Africa",
  "Ciudad del Cabo",
  "Cape Town",
  "Johannesburgo",
  "Johannesburg",
  "Kruger",
  "Kenia",
  "Kenya",
  "Nairobi",
  "Tanzania",
  "Zanzíbar",
  "Zanzibar",
  "Mauricio",
  "Mauritius",
  "Seychelles",
  "Madagascar",
  "Namibia",
  "Botsuana",
  "Botswana",
  // Oceanía
  "Australia",
  "Sídney",
  "Sydney",
  "Melbourne",
  "Brisbane",
  "Perth",
  "Cairns",
  "Nueva Zelanda",
  "New Zealand",
  "Auckland",
  "Queenstown",
  "Fiyi",
  "Fiji",
  "Polinesia",
  "Tahití",
  "Tahiti",
  "Bora Bora",
];

const NORMALIZED = new Map(
  TOP_DESTINATIONS.map((name) => [normalizePlace(name), name]),
);

export function normalizePlace(name: string): string {
  return name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim();
}

export function lookupDestination(token: string): string | null {
  return NORMALIZED.get(normalizePlace(token)) ?? null;
}
